### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by aqyx** [johanhermansson/letterboxd-exporter#3]
PS C:\Users\***\***\letterboxd-exporter-master> npm run taste-import

> letterboxed2taste@0.0.1 taste-import C:\Users\***\***\letterboxd-exporter-master
> node taste-import.js

HTTPError: Response code 422 (Unprocessable Entity)
    at EventEmitter.<anonymous> (C:\Users\***\***\letterboxd-exporter-master\node_modules\got\dist\source\as-promise.js:108:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by johanhermansson** [comment]
After one year of research (😉) I would say that Taste's API has changed, and the script needs to be updated 👎 

Sorry, this is not on my priority right now.
